add_newline = false

format = '󰣇 $username$all'

[character]
success_symbol = "[](bold blue)"
error_symbol = "[󰱶](bold red)"

[username]
disabled = false
show_always = true
format = '[\[$user\]](bold) '
